name: robank
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'SPRING_PROFILES_ACTIVE=docker'
      - 'FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}'
      - 'FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}'
      - 'FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}'
      - 'FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}'
      - 'FIREBASE_x509=${FIREBASE_x509}'
      - 'FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}'
    volumes:
      - ./uploads:/uploads

volumes:
  postgres-data: